appname: "VirtDancer"
charset: "UTF-8"
libvirt_uri: "qemu:///system"
users:
  admin:
    password: "$6$nXfcED59zMkW8FHH$YyrIV./6uVr1bqwZQVMAjX4BWSRN7ZXJl2asjVQIjgt4Iodx1apifupDTk8uY224u8BP0NnfFheUZgbaImbYi1"
    filters:
      prefix:
        - ""
      suffix:
      exact:
