#!/usr/bin/env perl

use strict;
use warnings;
use Term::ReadKey;

$| = 1;

ReadMode('noecho');
print STDERR "Password: ";
my $password = <STDIN>;
print STDERR "\nRepeat password: ";
my $pwcheck = <STDIN>;
ReadMode('restore');

chomp $password;
chomp $pwcheck;

if($password ne $pwcheck) {
    print STDERR "\nPasswords do not match!\n";
}
else {
    my @saltchars  = ('a'..'z', 'A'..'Z', 0..9);
    my $saltstring = '';
    $saltstring   .= $saltchars[rand @saltchars] for(1..16);

    my $hash = crypt($password, '$6$' . $saltstring . '$');
    print STDERR "\n";
    print $hash . "\n";
}
